-- =============================================================
-- Case ID: TC_LIBRARY_CLAUSE_SYN_001
-- Rule Type: Syntax
-- Related Rule ID: BNF_LIBRARY_CLAUSE
-- Standard Reference: IEEE 1076-2008 Section 13.2
-- Production: library_clause ::= library logical_name_list ;
-- Case Type: Positive
-- Test Focus: library_clause with multiple library references - the library keyword is followed by 3 logical_names (work/ieee/std), verifying logical_name_list can contain multiple comma-separated library names
-- Expected Result: Compiles successfully
-- Dependencies: None
-- =============================================================
entity syn001 is end entity; architecture bh of syn001 is type t_my is range 0 to 255; subtype t_sub is t_my range 0 to 15; type t_st is (A,B,C); type t_arr is array(0 to 7) of integer; type t_rc is record x:integer; y:t_st; end record; signal s:t_my:=0; signal ss:t_st:=A; begin s<=128; ss<=B; end architecture bh;